services:
  seed:
    image: ghcr.io/beda-software/fhir_seeder:2097655dada8044ed942a3167d26f136456660a7
    env_file:
      - .env
    volumes:
      - ./resources/seeds:/app/data
    command:
      - seed
      - "--server=${AIDBOX_BASE_URL}"
      - "--source=/app/data"
      - "--type=seeds"
      - "--username=${AIDBOX_CLIENT_ID}"
      - "--password=${AIDBOX_CLIENT_SECRET}"
