version: "3.7"
volumes:
  ips_pgdata:
    name: ips_pgdata
services:
  aidbox-db:
    image: healthsamurai/aidboxdb:16.1
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "ips_pgdata:/data:delegated"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"

  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on: ["aidbox-db"]
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
    env_file:
      - .env
    volumes:
      - ./zenproject:/zenproject

  seed:
    image: ghcr.io/beda-software/fhir_seeder:2097655dada8044ed942a3167d26f136456660a7
    env_file:
      - .env
    volumes:
      - ./resources/seeds:/app/data
    command:
      - seed
      - "--server=${AIDBOX_BASE_URL}"
      - "--source=/app/data"
      - "--type=seeds"
      - "--username=${AIDBOX_CLIENT_ID}"
      - "--password=${AIDBOX_CLIENT_SECRET}"

  node-app:
    hostname: node-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    user: node
    command: sh -c "rsync -ar /usr/src/app-cache/node_modules/. /usr/src/app/node_modules && pnpm run dev"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
